### ISSUE TITLE
Show when paste expires on view paste

### ISSUE THREAD

**Issue by jubal-R** [HackThisCode/CryptoPaste#12]
Could be nice to show when a paste expires when you view it rather than just when it was posted.

If you like the idea I could start working on it.

**Comment by jubal-R** [comment]
Was thinking something like [this](https://imgur.com/a/neayX).

Maybe add a count down timer as well.

**Comment by Kage** [comment]
Good idea.  I was deliberating on whether or not to incorporate this due to "security by obscurity".  I guess I could make that a configuration option as to whether or not to show expiry (similar to how you can configure showing the number of pastes in the footer or not).

**Comment by Kage** [comment]
I see you have a little bit of PHP background in your Github profile.  Would you be willing to submit a PR for this, or would you like myself/others to do so?  Either is fine, just asking for awareness.

**Comment by jubal-R** [comment]
I'll submit a PR for it.

**Comment by Kage** [comment]
Closed by PR #13
