### ISSUE TITLE
Month and Year expirations are off

### ISSUE THREAD

**Issue by jubal-R** [HackThisCode/CryptoPaste#15]
Noticed this when doing some testing.

The values in paste.php seem to be off.

1 Month should 2592000 seconds. (If we want to say 1 month is 30 days)

1 year should be 31536000 seconds.

**Comment by jubal-R** [comment]
I got those values from google so they may need testing. I can submit a PR later if you'd like.

**Comment by Kage** [comment]
Crap, you're right!  I'll fix this ASAP.
