### ISSUE TITLE
Captcha being covered by buttons

### ISSUE THREAD

**Issue by anshuman73** [HackThisCode/CryptoPaste#2]
The audio button and the refresh button covers a part of the Captcha, making it difficult to see (even for humans ;) )

In the example below, two characters were hidden

![capture](https://cloud.githubusercontent.com/assets/12889549/26362585/0b6aeeee-3ffc-11e7-800c-3d060403c3be.jpg)

**Comment by d1str0** [comment]
I also see this on Chrome 58 on macOS.

**Comment by Kage** [comment]
Closed by PR #8
