### ISSUE TITLE
CAPTCHA Error still shows after successfully submitting paste

### ISSUE THREAD

**Issue by d1str0** [HackThisCode/CryptoPaste#4]
<img width="1434" alt="screenshot 2017-05-24 21 01 45" src="https://cloud.githubusercontent.com/assets/3741618/26435456/3c53416e-40c4-11e7-9867-217d2ac7d25f.png">
This occurs after submitting a successful captcha AFTER failing it a few times.

Chrome 58 on macOS

**Comment by Kage** [comment]
Fixed in Symfony branch.

**Comment by Kage** [comment]
Fixed in v1.0 release.
