### ISSUE TITLE
AES CCM is inferior to GCM.

### ISSUE THREAD

**Issue by d1str0** [HackThisCode/CryptoPaste#6]
CCM is not nearly as common or secure as GCM. SJCL supports GCM.

https://crypto.stackexchange.com/questions/6842/how-to-choose-between-aes-ccm-and-aes-gcm-for-storage-volume-encryption

**Comment by Kage** [comment]
Good find, thank you.  Can you propose a PR, please?

**Comment by d1str0** [comment]
I will propose a PR as soon as I look into one other detail.

**Comment by Kage** [comment]
Closed by #14
