### ISSUE TITLE
Burn after reading shown as never expires

### ISSUE THREAD

**Issue by NotoriousOnes** [HackThisCode/CryptoPaste#9]
Hello there is a little bug,
I've uploaded using the "burn after reading" option and it works, 
still the expiration date is displayed as never:

![paste](https://user-images.githubusercontent.com/29272440/26974893-b71b4d50-4d1d-11e7-96b9-55d718413537.PNG)

Here is the process.json i get.

```javascript
{ status: "ok", url: "https://cryptopaste.org/1VEdPBE5", expires: "Never"}
```

This is not really a problem but could be an upgrade to add "Burn after reading" or "Once" instead of "Never".

I'm using chrome 58 and Windows 7.

**Comment by Kage** [comment]
Good catch, I'll work on a fix soon.
